apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: testing-project
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Test project playground
  sourceRepos:
  - '*'
  destinations:
  - namespace: argocd
    server: https://kubernetes.default.svc
    name: in-cluster
  sourceNamespaces:
  - "*"
