apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-sync-app
  namespace: argocd
spec:
  project: default
  sources:
   - repoURL: https://github.com/zilinjak/k8s-argocd-playground.git
     path: root-sync-apps
     targetRevision: HEAD
   - repoURL: https://github.com/zilinjak/k8s-argocd-playground.git
     path: root-sync-infra
     targetRevision: HEAD
   - repoURL: https://github.com/zilinjak/k8s-argocd-playground.git
     path: k8s-projects
     targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: {}
