apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra-project
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Test project playground, contains infra apps
  sourceRepos:
  - '*'
  destinations:
  - namespace: infra
    server: https://kubernetes.default.svc
    name: in-cluster
  sourceNamespaces:
  - "*"
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'